name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup msbuild
        uses: actions/setup-dotnet@v1
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
      
      - name: Restore NuGet packages
        run: dotnet restore ./sources/ConsoleTools.Core.sln
      
      - name: Build the solution
        run: dotnet build ./sources/ConsoleTools.Core.sln
